package day08

import common.io.inputFile
import common.io.readNonBlankLines
import io.kotest.matchers.shouldBe
import io.kotest.assertions.assertSoftly
import org.junit.jupiter.api.Test

class Day08Test {

  private val sample =
    """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """
      .trimIndent()

  private val simpleSample =
    """
    T.........
    ...T......
    .T........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    """
      .trimIndent()

  @Test
  fun `solve part one with sample input`() {
    part1(sample.lines()) shouldBe "14"
  }

  @Test
  fun `solve part two with simple sample input`() {
    part2(simpleSample.lines()) shouldBe "9"
  }

  @Test
  fun `solve part two with complex sample input`() {
    part2(sample.lines()) shouldBe "34"
  }

  @Test
  fun `solve puzzle`() {
    val input = inputFile("day08.txt").readNonBlankLines()
    assertSoftly {
      part1(input) shouldBe "379"
      part2(input) shouldBe "ANSWER2"
    }
  }

}
