#!/usr/bin/env just --justfile

add-module module:
  ./scripts/add-module.sh {{module}}

list-dependency-updates module="":
  ./gradlew {{module}}:dependencyUpdates

get-input year day:
  ./scripts/get-input.sh {{year}} {{day}}

init-day year day: (get-input year day)
  ./scripts/init-day.sh {{year}} {{day}}
